<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20251216103914 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Создание Folder, Status и Task энтити';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE folders (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description VARCHAR(1000) DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE statuses (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR(255) NOT NULL, priority BIGINT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE TABLE tasks (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(50) NOT NULL, description VARCHAR(1000) DEFAULT NULL, status_id INT DEFAULT NULL, folder_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_505865976BF700BD ON tasks (status_id)');
        $this->addSql('CREATE INDEX IDX_50586597162CB942 ON tasks (folder_id)');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_505865976BF700BD FOREIGN KEY (status_id) REFERENCES statuses (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE tasks ADD CONSTRAINT FK_50586597162CB942 FOREIGN KEY (folder_id) REFERENCES folders (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_505865976BF700BD');
        $this->addSql('ALTER TABLE tasks DROP CONSTRAINT FK_50586597162CB942');
        $this->addSql('DROP TABLE folders');
        $this->addSql('DROP TABLE statuses');
        $this->addSql('DROP TABLE tasks');
    }
}
